// Generated by Cypress Author on 2026-10-07.
import { TaskFormCard } from "@/components/TaskFormCard";
import { createFakeTaskApi, type FakeTaskApi } from "../support/fakeTaskApi";

const EMPTY = { title: "", description: "" };

describe("Create task flow", () => {
  let api: FakeTaskApi;

  // A fresh fake backend per test keeps every test independent.
  beforeEach(() => {
    api = createFakeTaskApi();
    cy.spy(api, "create").as("create");
    cy.mount(<TaskFormCard heading="New task" action={api.create} initial={EMPTY} submitLabel="Create" />);
  });

  it("fill title and description, submit → task is saved and the user is sent back to /tasks", () => {
    cy.contains("h2", "New task").should("be.visible");
    cy.get("[data-cy=title-input]").type("Buy milk");
    cy.get("[data-cy=description-input]").type("2 litres, semi-skimmed");
    cy.get("[data-cy=submit]").click();

    cy.wrap(api.tasks).should("have.length", 1);
    cy.wrap(api.tasks).its(0).should("include", { title: "Buy milk", description: "2 litres, semi-skimmed" });
    cy.wrap(api).its("navigatedTo").should("eq", "/tasks");
    cy.get("[data-cy=form-error]").should("not.exist");
  });

  it("title only → saved with an empty description", () => {
    cy.get("[data-cy=title-input]").type("Just a title");
    cy.get("[data-cy=submit]").click();

    cy.wrap(api.tasks).its(0).should("include", { title: "Just a title", description: "" });
  });

  it("surrounding whitespace → trimmed before saving", () => {
    cy.get("[data-cy=title-input]").type("   Padded title   ");
    cy.get("[data-cy=description-input]").type("  padded body  ");
    cy.get("[data-cy=submit]").click();

    cy.wrap(api.tasks).its(0).should("include", { title: "Padded title", description: "padded body" });
  });

  it("title and description at their maximum lengths → accepted", () => {
    const title = "t".repeat(120);
    const description = "d".repeat(2000);
    // Set values directly: typing 2,000 characters one by one would only slow the test down.
    cy.get("[data-cy=title-input]").invoke("val", title);
    cy.get("[data-cy=description-input]").invoke("val", description);
    cy.get("[data-cy=submit]").click();

    cy.wrap(api.tasks).its(0).should("include", { title, description });
  });

  it("whitespace-only title → server rejects it, nothing is saved, then fixing the title succeeds", () => {
    cy.get("[data-cy=title-input]").type("     ");
    cy.get("[data-cy=description-input]").type("keep this text");
    cy.get("[data-cy=submit]").click();

    cy.get("[data-cy=form-error]").should("have.text", "Title is required");
    cy.get("[data-cy=description-input]").should("have.value", "keep this text");
    cy.wrap(api.tasks).should("have.length", 0);
    cy.wrap(api).its("navigatedTo").should("be.null");

    cy.get("[data-cy=title-input]").clear().type("Now valid");
    cy.get("[data-cy=submit]").click();

    cy.wrap(api.tasks).should("have.length", 1);
    cy.get("[data-cy=form-error]").should("not.exist");
    cy.wrap(api).its("navigatedTo").should("eq", "/tasks");
  });

  it("empty title → browser validation stops the submission before reaching the server", () => {
    cy.get("[data-cy=description-input]").type("no title");
    cy.get("[data-cy=submit]").click();

    cy.get("@create").should("not.have.been.called");
    cy.wrap(api.tasks).should("have.length", 0);
  });

  it("database failure → friendly error with input kept, retry succeeds", () => {
    api.failNext = true;
    cy.get("[data-cy=title-input]").type("Flaky save");
    cy.get("[data-cy=submit]").click();

    cy.get("[data-cy=form-error]").should("have.text", "Could not save the task. Please try again.");
    cy.get("[data-cy=title-input]").should("have.value", "Flaky save");
    cy.wrap(api.tasks).should("have.length", 0);

    cy.get("[data-cy=submit]").click();

    cy.wrap(api.tasks).should("have.length", 1);
    cy.get("[data-cy=form-error]").should("not.exist");
  });

  it("slow save → button is disabled with 'Saving…' so the task cannot be created twice", () => {
    const release = api.holdNext();
    cy.get("[data-cy=title-input]").type("Slow one");
    cy.get("[data-cy=submit]").click();

    cy.get("[data-cy=submit]").should("be.disabled").and("have.text", "Saving…");
    cy.wrap(api.tasks).should("have.length", 0);

    cy.then(release);

    cy.wrap(api.tasks).should("have.length", 1);
    cy.get("@create").should("have.been.calledOnce");
  });

  it("Cancel → links back to /tasks without saving anything", () => {
    cy.get("[data-cy=title-input]").type("Never saved");

    cy.get("[data-cy=cancel]").should("have.attr", "href", "/tasks");
    cy.get("@create").should("not.have.been.called");
    cy.wrap(api.tasks).should("have.length", 0);
  });
});
