// Generated by Cypress Author on 2026-10-07.
import { DeleteTaskView } from "@/components/DeleteTaskView";
import { makeTask } from "../support/factories";

describe("DeleteTaskView", () => {
  it("renders the confirmation → names the task and offers Cancel and Delete without deleting yet", () => {
    cy.mount(<DeleteTaskView task={makeTask({ title: "Old report" })} action={cy.stub().as("action")} />);

    cy.contains("h2", "Delete task?").should("be.visible");
    cy.contains("“Old report” will be permanently removed.").should("be.visible");
    cy.get("[data-cy=cancel]").should("have.attr", "href", "/tasks");
    cy.get("[data-cy=confirm-delete]").should("be.visible").and("be.enabled");
    cy.get("@action").should("not.have.been.called");
  });

  it("Delete clicked → runs the delete action exactly once", () => {
    cy.mount(<DeleteTaskView task={makeTask()} action={cy.stub().as("action")} />);

    cy.get("[data-cy=confirm-delete]").click();

    cy.get("@action").should("have.been.calledOnce");
  });

  it("Cancel clicked → does not run the delete action", () => {
    cy.mount(<DeleteTaskView task={makeTask()} action={cy.stub().as("action")} />);
    // Cancel is a link; block the navigation so the test frame stays put.
    cy.get("[data-cy=cancel]").then(($a) => $a[0].addEventListener("click", (e) => e.preventDefault()));

    cy.get("[data-cy=cancel]").click();

    cy.get("@action").should("not.have.been.called");
  });

  it("title with HTML → shown as literal text", () => {
    cy.mount(<DeleteTaskView task={makeTask({ title: "<b>x</b>" })} action={cy.stub()} />);

    cy.contains("“<b>x</b>” will be permanently removed.").should("exist");
    cy.get("section b").should("not.exist");
  });
});
