// Generated by Cypress Author on 2026-10-07.
import { DeleteTaskView } from "@/components/DeleteTaskView";
import { createFakeTaskApi, type FakeTaskApi } from "../support/fakeTaskApi";
import { makeTask } from "../support/factories";

describe("Delete task flow", () => {
  let api: FakeTaskApi;
  const target = () => makeTask({ id: 7, title: "Old report" });

  // A fresh fake backend with the target task plus a bystander per test.
  beforeEach(() => {
    api = createFakeTaskApi([target(), makeTask({ id: 8, title: "Keep me" })]);
    // Spy on the bound action the form actually calls (not the factory that creates it).
    const remove = cy.stub().as("remove").callsFake(api.remove(7));
    cy.mount(<DeleteTaskView task={target()} action={remove} />);
  });

  it("opens as a confirmation → names the task and has not deleted anything yet", () => {
    cy.contains("“Old report” will be permanently removed.").should("be.visible");
    cy.wrap(api.tasks).should("have.length", 2);
    cy.wrap(api).its("navigatedTo").should("be.null");
  });

  it("confirm Delete → only that task is removed and the user is sent back to /tasks", () => {
    cy.get("[data-cy=confirm-delete]").click();

    cy.wrap(api.tasks).should("have.length", 1);
    cy.wrap(api.tasks).its(0).should("include", { id: 8, title: "Keep me" });
    cy.wrap(api).its("navigatedTo").should("eq", "/tasks");
  });

  it("Cancel → keeps every task and links back to /tasks", () => {
    cy.get("[data-cy=cancel]").should("have.attr", "href", "/tasks").then(($a) => $a[0].addEventListener("click", (e) => e.preventDefault()));
    cy.get("[data-cy=cancel]").click();

    cy.get("@remove").should("not.have.been.called");
    cy.wrap(api.tasks).should("have.length", 2);
  });

  it("task already deleted elsewhere → confirming is harmless and still returns to /tasks", () => {
    api.removeFromStore(7);

    cy.get("[data-cy=confirm-delete]").click();

    cy.wrap(api).its("navigatedTo").should("eq", "/tasks");
    cy.wrap(api.tasks).should("have.length", 1);
  });
});
