// Generated by Cypress Author on 2026-10-07.
import { TaskFormCard } from "@/components/TaskFormCard";
import { createFakeTaskApi, type FakeTaskApi } from "../support/fakeTaskApi";
import { makeTask } from "../support/factories";

describe("Edit task flow", () => {
  let api: FakeTaskApi;
  const original = () =>
    makeTask({ id: 7, title: "Write report", description: "Draft intro", createdAt: "2026-10-01T08:00:00.000Z", updatedAt: "2026-10-01T08:00:00.000Z" });

  // A fresh fake backend (with a second task to prove it stays untouched) per test.
  beforeEach(() => {
    api = createFakeTaskApi([original(), makeTask({ id: 8, title: "Other task", description: "Leave me alone" })]);
    // Spy on the bound action the form actually calls (not the factory that creates it).
    const update = cy.stub().as("update").callsFake(api.update(7));
    cy.mount(
      <TaskFormCard
        heading="Edit task"
        action={update}
        initial={{ title: "Write report", description: "Draft intro" }}
        submitLabel="Save"
      />,
    );
  });

  const task = () => api.tasks.find((t) => t.id === 7)!;

  it("opens prefilled with the current values and a 'Save' button", () => {
    cy.contains("h2", "Edit task").should("be.visible");
    cy.get("[data-cy=title-input]").should("have.value", "Write report");
    cy.get("[data-cy=description-input]").should("have.value", "Draft intro");
    cy.get("[data-cy=submit]").should("have.text", "Save");
  });

  it("change the title only → title and updated time change, description and created time stay, other tasks untouched", () => {
    cy.get("[data-cy=title-input]").clear().type("Write final report");
    cy.get("[data-cy=submit]").click();

    cy.wrap(api).its("navigatedTo").should("eq", "/tasks");
    cy.then(() => {
      expect(task().title).to.equal("Write final report");
      expect(task().description).to.equal("Draft intro");
      expect(task().createdAt).to.equal("2026-10-01T08:00:00.000Z");
      expect(task().updatedAt).not.to.equal("2026-10-01T08:00:00.000Z");
      expect(api.tasks.find((t) => t.id === 8)).to.include({ title: "Other task", description: "Leave me alone" });
    });
  });

  it("change the description only → description is saved and the title is kept", () => {
    cy.get("[data-cy=description-input]").clear().type("Rewritten body");
    cy.get("[data-cy=submit]").click();

    cy.wrap(api).its("navigatedTo").should("eq", "/tasks");
    cy.then(() => expect(task()).to.include({ title: "Write report", description: "Rewritten body" }));
  });

  it("clear the description → saved as empty", () => {
    cy.get("[data-cy=description-input]").clear();
    cy.get("[data-cy=submit]").click();

    cy.wrap(api).its("navigatedTo").should("eq", "/tasks");
    cy.then(() => expect(task().description).to.equal(""));
  });

  it("whitespace-only title → error shown, typed text kept and the stored task unchanged", () => {
    cy.get("[data-cy=title-input]").clear().type("    ");
    cy.get("[data-cy=submit]").click();

    cy.get("[data-cy=form-error]").should("have.text", "Title is required");
    cy.get("[data-cy=description-input]").should("have.value", "Draft intro");
    cy.then(() => {
      expect(task().title).to.equal("Write report");
      expect(api.navigatedTo).to.equal(null);
    });
  });

  it("empty title → browser validation blocks the request", () => {
    cy.get("[data-cy=title-input]").clear();
    cy.get("[data-cy=submit]").click();

    cy.get("@update").should("not.have.been.called");
  });

  it("title over the limit → input cannot exceed 120 characters", () => {
    cy.get("[data-cy=title-input]").clear().type("x".repeat(130), { delay: 0 }).invoke("val").should("have.length", 120);
  });

  it("task deleted in the meantime → 'no longer exists' error with the user's edits kept", () => {
    api.removeFromStore(7);
    cy.get("[data-cy=title-input]").clear().type("Edited too late");
    cy.get("[data-cy=submit]").click();

    cy.get("[data-cy=form-error]").should("have.text", "This task no longer exists.");
    cy.get("[data-cy=title-input]").should("have.value", "Edited too late");
    cy.then(() => expect(api.navigatedTo).to.equal(null));
  });

  it("database failure → friendly error, then retry saves the change", () => {
    api.failNext = true;
    cy.get("[data-cy=title-input]").clear().type("Retry me");
    cy.get("[data-cy=submit]").click();

    cy.get("[data-cy=form-error]").should("have.text", "Could not save the task. Please try again.");
    cy.then(() => expect(task().title).to.equal("Write report"));

    cy.get("[data-cy=submit]").click();

    cy.wrap(api).its("navigatedTo").should("eq", "/tasks");
    cy.then(() => expect(task().title).to.equal("Retry me"));
  });

  it("slow save → button is disabled with 'Saving…' until the server answers", () => {
    const release = api.holdNext();
    cy.get("[data-cy=title-input]").clear().type("Slow edit");
    cy.get("[data-cy=submit]").click();

    cy.get("[data-cy=submit]").should("be.disabled").and("have.text", "Saving…");
    cy.then(() => expect(task().title).to.equal("Write report"));

    cy.then(release);

    cy.wrap(api).its("navigatedTo").should("eq", "/tasks");
    cy.get("@update").should("have.been.calledOnce");
  });

  it("Cancel → links back to /tasks and changes nothing", () => {
    cy.get("[data-cy=title-input]").clear().type("Discarded");

    cy.get("[data-cy=cancel]").should("have.attr", "href", "/tasks");
    cy.get("@update").should("not.have.been.called");
    cy.then(() => expect(task().title).to.equal("Write report"));
  });
});
