// Generated by Cypress Author on 2026-10-07.
import { MainNav } from "@/components/MainNav";
import { SiteHeader } from "@/components/SiteHeader";

describe("SiteHeader", () => {
  beforeEach(() => {
    cy.mountAt("/", <SiteHeader />);
  });

  it("header → logo links home, nav lists Tasks, 'New task' stays, and there is no Home link", () => {
    cy.get("h1 a").should("have.attr", "href", "/").and("have.text", "AIcomplish");
    cy.get("nav[aria-label=Main] a").should("have.length", 1).first().should("have.text", "Tasks").and("have.attr", "href", "/tasks");
    cy.contains("a", "+ New task").should("have.attr", "href", "/tasks/new");
    cy.contains("a", /^Home$/).should("not.exist");
  });
});

describe("MainNav active state", () => {
  ["/tasks", "/tasks/new", "/tasks/12/edit"].forEach((path) => {
    it(`at ${path} → Tasks is marked as the current section`, () => {
      cy.mountAt(path, <MainNav />);

      cy.contains("a", "Tasks").should("have.attr", "aria-current", "page");
    });
  });

  ["/", "/tasks-archive"].forEach((path) => {
    it(`at ${path} → Tasks is not marked as current`, () => {
      cy.mountAt(path, <MainNav />);

      cy.contains("a", "Tasks").should("not.have.attr", "aria-current");
    });
  });

  it("active vs inactive → the current link is visually distinct", () => {
    cy.mountAt("/tasks", <MainNav />);
    cy.contains("a", "Tasks").invoke("css", "color").as("activeColor");

    cy.mountAt("/", <MainNav />);
    cy.contains("a", "Tasks").invoke("css", "color").then(function (inactive) {
      expect(inactive).not.to.equal(this.activeColor);
    });
  });
});
