// Generated by Cypress Author on 2026-10-07.
import NotFound from "@/app/not-found";

describe("NotFound", () => {
  it("unknown task → explains it and links back to the tasks list", () => {
    cy.mount(<NotFound />);

    cy.contains("h2", "Not found").should("be.visible");
    cy.contains("That task doesn’t exist.").should("be.visible");
    cy.contains("a", "Back to tasks").should("have.attr", "href", "/tasks");
  });
});
