// Generated by Cypress Author on 2026-10-07.
import { Pagination } from "@/components/Pagination";

describe("Pagination", () => {
  it("single page → renders nothing", () => {
    cy.mount(<Pagination page={1} totalPages={1} query="" />);

    cy.get("[data-cy=pagination]").should("not.exist");
  });

  it("first page → only an 'Older' link to page 2 and the page indicator", () => {
    cy.mount(<Pagination page={1} totalPages={3} query="" />);

    cy.get("[data-cy=page-info]").should("have.text", "Page 1 of 3");
    cy.contains("a", "Older →").should("have.attr", "href", "/tasks?page=2").and("have.attr", "rel", "next");
    cy.contains("a", "← Newer").should("not.exist");
  });

  it("middle page → 'Newer' returns to the bare list URL and 'Older' goes to the next page", () => {
    cy.mount(<Pagination page={2} totalPages={3} query="" />);

    cy.get("[data-cy=page-info]").should("have.text", "Page 2 of 3");
    cy.contains("a", "← Newer").should("have.attr", "href", "/tasks").and("have.attr", "rel", "prev");
    cy.contains("a", "Older →").should("have.attr", "href", "/tasks?page=3");
  });

  it("last page → only a 'Newer' link", () => {
    cy.mount(<Pagination page={3} totalPages={3} query="" />);

    cy.contains("a", "← Newer").should("have.attr", "href", "/tasks?page=2");
    cy.contains("a", "Older →").should("not.exist");
  });

  it("active search → query is preserved and URL-encoded in both links", () => {
    cy.mount(<Pagination page={2} totalPages={3} query="milk & eggs" />);

    cy.contains("a", "← Newer").should("have.attr", "href", "/tasks?q=milk+%26+eggs");
    cy.contains("a", "Older →").should("have.attr", "href", "/tasks?q=milk+%26+eggs&page=3");
  });
});
