// Generated by Cypress Author on 2026-10-07.
import { TasksView } from "@/components/TasksView";
import { makePage, makeTask, makeTasks } from "../support/factories";

describe("TasksView", () => {
  it("tasks present → lists every task with a plural count", () => {
    cy.mount(<TasksView result={makePage({ tasks: makeTasks(3) })} query="" />);

    cy.get("[data-cy=summary]").should("have.text", "3 tasks");
    cy.get("[data-cy=task-item]").should("have.length", 3);
    cy.get("[data-cy=task-title]").first().should("have.text", "Task 3");
    cy.get("[data-cy=empty-state]").should("not.exist");
  });

  it("a single task → singular count", () => {
    cy.mount(<TasksView result={makePage({ tasks: [makeTask()] })} query="" />);

    cy.get("[data-cy=summary]").should("have.text", "1 task");
  });

  it("no tasks and no search → invites the user to create the first task", () => {
    cy.mount(<TasksView result={makePage({ tasks: [], total: 0 })} query="" />);

    cy.get("[data-cy=summary]").should("have.text", "0 tasks");
    cy.get("[data-cy=empty-state]").should("contain.text", "Nothing here yet").and("contain.text", "Create your first task");
    cy.get("[data-cy=task-item]").should("not.exist");
  });

  it("search without matches → shows the query and a 'no matching tasks' state", () => {
    cy.mount(<TasksView result={makePage({ tasks: [], total: 0 })} query="zzz" />);

    cy.get("[data-cy=summary]").should("have.text", "0 tasks matching “zzz”");
    cy.get("[data-cy=empty-state]").should("contain.text", "No matching tasks").and("contain.text", "Try a different search.");
  });

  it("search form → is a GET form to /tasks, prefilled with the active query", () => {
    cy.mount(<TasksView result={makePage()} query="milk" />);

    cy.get("form[role=search]").should("have.attr", "action", "/tasks").and("not.have.attr", "method", "post");
    cy.get("input[type=search]").should("have.attr", "name", "q").and("have.value", "milk").and("have.attr", "aria-label", "Search tasks");
  });

  it("typing a search and pressing Enter → submits the term as the `q` parameter", () => {
    cy.mount(<TasksView result={makePage()} query="" />);
    const submitted = cy.stub().as("submitted");
    // Intercept the native submit so the test iframe does not navigate away.
    cy.get("form[role=search]").then(($form) => {
      $form[0].addEventListener("submit", (e) => {
        e.preventDefault();
        submitted(Object.fromEntries(new FormData(e.target as HTMLFormElement)));
      });
    });

    cy.get("input[type=search]").type("buy milk{enter}");

    cy.get("@submitted").should("have.been.calledOnceWith", { q: "buy milk" });
  });

  it("clicking the Search button → submits the form too", () => {
    cy.mount(<TasksView result={makePage()} query="" />);
    const submitted = cy.stub().as("submitted");
    cy.get("form[role=search]").then(($form) => {
      $form[0].addEventListener("submit", (e) => {
        e.preventDefault();
        submitted(Object.fromEntries(new FormData(e.target as HTMLFormElement)));
      });
    });

    cy.get("input[type=search]").type("eggs");
    cy.contains("button", "Search").click();

    cy.get("@submitted").should("have.been.calledOnceWith", { q: "eggs" });
  });

  it("multiple pages → shows pagination that keeps the query; single page → none", () => {
    cy.mount(<TasksView result={makePage({ page: 2, totalPages: 3, total: 70 })} query="milk" />);
    cy.contains("a", "Older →").should("have.attr", "href", "/tasks?q=milk&page=3");

    cy.mount(<TasksView result={makePage({ page: 1, totalPages: 1 })} query="milk" />);
    cy.get("[data-cy=pagination]").should("not.exist");
  });
});
