// Generated by Cypress Author on 2026-10-07.
import type { FormState } from "@/app/actions";
import { TaskForm } from "@/components/TaskForm";

const EMPTY: FormState["values"] = { title: "", description: "" };

/** A Server Action stand-in that resolves with the state it is given. */
const okAction = (state: FormState) => cy.stub().as("action").resolves(state);

describe("TaskForm", () => {
  it("create mode → empty, labelled, size-limited fields with the title focused", () => {
    cy.mount(<TaskForm action={okAction({ error: null, values: EMPTY })} initial={EMPTY} submitLabel="Create" />);

    cy.contains("label", "Title").find("input").should("have.value", "").and("have.attr", "maxlength", "120").and("have.attr", "required");
    cy.contains("label", "Description").find("textarea").should("have.value", "").and("have.attr", "maxlength", "2000");
    cy.get("[data-cy=title-input]").should("have.focus");
    cy.get("[data-cy=submit]").should("have.text", "Create").and("be.enabled");
    cy.get("[data-cy=cancel]").should("have.attr", "href", "/tasks");
    cy.get("[data-cy=form-error]").should("not.exist");
  });

  it("edit mode → prefilled with the task's values and a custom submit label", () => {
    const initial = { title: "Write report", description: "Draft intro" };
    cy.mount(<TaskForm action={okAction({ error: null, values: initial })} initial={initial} submitLabel="Save" />);

    cy.get("[data-cy=title-input]").should("have.value", "Write report");
    cy.get("[data-cy=description-input]").should("have.value", "Draft intro");
    cy.get("[data-cy=submit]").should("have.text", "Save");
  });

  it("valid input submitted → action receives the initial state and the entered form data once", () => {
    cy.mount(<TaskForm action={okAction({ error: null, values: EMPTY })} initial={EMPTY} submitLabel="Create" />);

    cy.get("[data-cy=title-input]").type("Buy milk");
    cy.get("[data-cy=description-input]").type("2 litres");
    cy.get("[data-cy=submit]").click();

    cy.get("@action").should("have.been.calledOnce");
    cy.get("@action").then((stub) => {
      const [prev, formData] = (stub as unknown as sinon.SinonStub).firstCall.args as [FormState, FormData];
      expect(prev).to.deep.equal({ error: null, values: EMPTY });
      expect(formData.get("title")).to.equal("Buy milk");
      expect(formData.get("description")).to.equal("2 litres");
    });
  });

  it("empty title → browser validation blocks submit and the action is never called", () => {
    cy.mount(<TaskForm action={okAction({ error: null, values: EMPTY })} initial={EMPTY} submitLabel="Create" />);

    cy.get("[data-cy=submit]").click();

    cy.get("[data-cy=title-input]").then(($el) => expect(($el[0] as HTMLInputElement).validity.valueMissing).to.be.true);
    cy.get("@action").should("not.have.been.called");
  });

  it("title longer than the limit → input refuses extra characters", () => {
    cy.mount(<TaskForm action={okAction({ error: null, values: EMPTY })} initial={EMPTY} submitLabel="Create" />);

    cy.get("[data-cy=title-input]").type("x".repeat(130), { delay: 0 }).invoke("val").should("have.length", 120);
  });

  it("server returns a validation error → shows it as an alert and keeps what the user typed", () => {
    const returned: FormState = { error: "Title is too long", values: { title: "Kept title", description: "Kept description" } };
    cy.mount(<TaskForm action={okAction(returned)} initial={EMPTY} submitLabel="Create" />);

    cy.get("[data-cy=title-input]").type("Kept title");
    cy.get("[data-cy=description-input]").type("Kept description");
    cy.get("[data-cy=submit]").click();

    cy.get("[data-cy=form-error]").should("have.attr", "role", "alert").and("have.text", "Title is too long");
    cy.get("[data-cy=title-input]").should("have.value", "Kept title");
    cy.get("[data-cy=description-input]").should("have.value", "Kept description");
  });

  it("submission in flight → button shows 'Saving…' and is disabled until the action settles", () => {
    let settle!: (state: FormState) => void;
    const pending = new Promise<FormState>((resolve) => (settle = resolve));
    cy.mount(<TaskForm action={cy.stub().as("action").returns(pending)} initial={EMPTY} submitLabel="Create" />);

    cy.get("[data-cy=title-input]").type("Slow task");
    cy.get("[data-cy=submit]").click();

    cy.get("[data-cy=submit]").should("be.disabled").and("have.text", "Saving…");

    cy.then(() => settle({ error: null, values: { title: "Slow task", description: "" } }));
    cy.get("[data-cy=submit]").should("be.enabled").and("have.text", "Create");
  });
});
