// Generated by Cypress Author on 2026-10-07.
import { TaskItem } from "@/components/TaskItem";
import { makeTask } from "../support/factories";

describe("TaskItem", () => {
  it("shows title, description and accessible edit/delete links → links point to the task's routes", () => {
    cy.mount(<TaskItem task={makeTask({ id: 42, title: "Buy milk", description: "2 litres" })} />);

    cy.get("[data-cy=task-title]").should("have.text", "Buy milk");
    cy.get("[data-cy=task-description]").should("have.text", "2 litres");
    cy.get("a[aria-label='Edit Buy milk']").should("have.attr", "href", "/tasks/42/edit");
    cy.get("a[aria-label='Delete Buy milk']").should("have.attr", "href", "/tasks/42/delete");
  });

  it("task without description → no description element is rendered", () => {
    cy.mount(<TaskItem task={makeTask({ description: "" })} />);

    cy.get("[data-cy=task-title]").should("be.visible");
    cy.get("[data-cy=task-description]").should("not.exist");
    cy.get("[data-cy=task-details]").should("not.exist");
  });

  it("short description → shown inline without a 'show more' toggle", () => {
    cy.mount(<TaskItem task={makeTask({ description: "Line 1\nLine 2\nLine 3" })} />);

    cy.get("[data-cy=task-description]").should("be.visible");
    cy.get("[data-cy=task-details]").should("not.exist");
  });

  it("long description → collapsed by default, expands to the full text when toggled", () => {
    const long = "word ".repeat(60).trim(); // > 160 characters
    cy.mount(<TaskItem task={makeTask({ description: long })} />);

    cy.get("[data-cy=task-details]").should("not.have.attr", "open");
    cy.get("[data-cy=task-description-full]").should("not.be.visible");

    cy.get("[data-cy=task-details] summary").click();

    cy.get("[data-cy=task-details]").should("have.attr", "open");
    cy.get("[data-cy=task-description-full]").should("be.visible").and("have.text", long);
  });

  it("description with more than three lines → treated as long and collapsible", () => {
    cy.mount(<TaskItem task={makeTask({ description: "a\nb\nc\nd" })} />);

    cy.get("[data-cy=task-details]").should("exist").and("not.have.attr", "open");
  });

  it("task with timestamps → shows the updated time and exposes created/updated in the tooltip", () => {
    cy.mount(<TaskItem task={makeTask({ createdAt: "2026-10-01T08:00:00.000Z", updatedAt: "2026-10-07T20:43:00.000Z" })} />);

    cy.get("[data-cy=task-updated]")
      .should("have.prop", "tagName", "TIME")
      .and("have.attr", "datetime", "2026-10-07T20:43:00.000Z")
      .invoke("text")
      .should("match", /^Updated [A-Z][a-z]{2} \d{1,2}, /);
    cy.get("[data-cy=task-updated]").invoke("attr", "title").should("match", /Created .*\nUpdated /);
  });

  it("edit and delete icons → are colored by default (accent / danger) so they read as actions", () => {
    cy.mount(<TaskItem task={makeTask()} />);

    cy.cssColor("--accent").then((accent) => {
      cy.get("[data-cy=edit-task]").should("have.css", "color", accent);
    });
    cy.cssColor("--danger").then((danger) => {
      cy.get("[data-cy=delete-task]").should("have.css", "color", danger);
    });
  });

  it("title and description containing HTML → rendered as literal text, not markup", () => {
    cy.mount(<TaskItem task={makeTask({ title: "<i>bold</i>", description: "<b>x</b>" })} />);

    cy.get("[data-cy=task-title]").should("have.text", "<i>bold</i>");
    cy.get("[data-cy=task-description]").should("have.text", "<b>x</b>").find("b").should("not.exist");
  });
});
