// Generated by Cypress Author on 2026-10-07.
import { TodayView } from "@/components/TodayView";
import { makeTask, makeTasks } from "../support/factories";

describe("TodayView", () => {
  it("with tasks → shows the date, heading, count and latest tasks with a 'View all' link", () => {
    cy.mount(<TodayView tasks={makeTasks(5)} total={12} dateLabel="Wednesday, October 7" />);

    cy.get("[data-cy=date]").should("have.text", "Wednesday, October 7");
    cy.contains("h2", "Today").should("be.visible");
    cy.get("[data-cy=summary]").should("have.text", "You have 12 tasks.");
    cy.contains("h3", "Latest tasks").should("be.visible");
    cy.get("[data-cy=task-item]").should("have.length", 5);
    cy.contains("a", "View all →").should("have.attr", "href", "/tasks");
    cy.get("[data-cy=empty-state]").should("not.exist");
  });

  it("exactly one task → singular wording", () => {
    cy.mount(<TodayView tasks={[makeTask()]} total={1} dateLabel="Monday, January 1" />);

    cy.get("[data-cy=summary]").should("have.text", "You have 1 task.");
  });

  it("no tasks → friendly empty state linking to task creation, without the list or 'View all'", () => {
    cy.mount(<TodayView tasks={[]} total={0} dateLabel="Monday, January 1" />);

    cy.get("[data-cy=summary]").should("have.text", "You have no tasks yet.");
    cy.get("[data-cy=empty-state]").contains("a", "Create your first task").should("have.attr", "href", "/tasks/new");
    cy.get("[data-cy=task-item]").should("not.exist");
    cy.contains("a", "View all").should("not.exist");
  });
});
