/**
 * Global component-test support: design tokens, `cy.mount` and shared helpers.
 * Generated by Cypress Author on 2026-10-07.
 */
import "@/app/globals.css";
import { mount } from "cypress/react";
import type { ReactNode } from "react";
import { PathnameProvider } from "./stubs/next-navigation";

Cypress.Commands.add("mount", mount);

/** Mounts `ui` as if the app were currently at `pathname` (drives NavLink active state). */
Cypress.Commands.add("mountAt", (pathname: string, ui: ReactNode) =>
  mount(<PathnameProvider value={pathname}>{ui}</PathnameProvider>),
);

/** Resolves a CSS custom property (e.g. `--accent`) to the computed `rgb(...)` color string. */
Cypress.Commands.add("cssColor", (token: string) =>
  cy.document().then((doc) => {
    const probe = doc.createElement("span");
    probe.style.color = `var(${token})`;
    doc.body.append(probe);
    const color = getComputedStyle(probe).color;
    probe.remove();
    return color;
  }),
);

declare global {
  // eslint-disable-next-line @typescript-eslint/no-namespace
  namespace Cypress {
    interface Chainable {
      mount: typeof mount;
      mountAt(pathname: string, ui: ReactNode): ReturnType<typeof mount>;
      cssColor(token: string): Chainable<string>;
    }
  }
}
